/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CGtGuiEZVz7
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"

export function ChatUI() {
  return (
    <div className="flex h-screen">
      <div className="bg-gray-100 dark:bg-gray-800 w-64 border-r border-gray-200 dark:border-gray-700 p-4 overflow-auto">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-medium text-gray-900 dark:text-gray-50">Recent Chats</h2>
          <Button size="icon" variant="ghost">
            <PlusIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
          </Button>
        </div>
        <div className="space-y-2">
          <div className="flex items-center gap-3 cursor-pointer hover:bg-gray-200 dark:hover:bg-gray-700 rounded-md p-2">
            <Avatar className="h-10 w-10">
              <AvatarImage alt="User Avatar" src="/placeholder-avatar.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div>
              <p className="font-medium text-gray-900 dark:text-gray-50">John Doe</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">Hello, how can I help you?</p>
            </div>
          </div>
          <div className="flex items-center gap-3 cursor-pointer hover:bg-gray-200 dark:hover:bg-gray-700 rounded-md p-2">
            <Avatar className="h-10 w-10">
              <AvatarImage alt="User Avatar" src="/placeholder-avatar.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div>
              <p className="font-medium text-gray-900 dark:text-gray-50">Jane Smith</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">I have a question about machine learning.</p>
            </div>
          </div>
          <div className="flex items-center gap-3 cursor-pointer hover:bg-gray-200 dark:hover:bg-gray-700 rounded-md p-2">
            <Avatar className="h-10 w-10">
              <AvatarImage alt="User Avatar" src="/placeholder-avatar.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div>
              <p className="font-medium text-gray-900 dark:text-gray-50">Michael Johnson</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">Can you explain neural networks to me?</p>
            </div>
          </div>
          <div className="flex items-center gap-3 cursor-pointer hover:bg-gray-200 dark:hover:bg-gray-700 rounded-md p-2">
            <Avatar className="h-10 w-10">
              <AvatarImage alt="User Avatar" src="/placeholder-avatar.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div>
              <p className="font-medium text-gray-900 dark:text-gray-50">Emily Davis</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                I'm interested in learning about machine learning algorithms.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div className="flex flex-col flex-1">
        <header className="flex items-center justify-between bg-gray-900 px-4 py-3 text-white shadow">
          <div className="flex items-center gap-2">
            <BotIcon className="h-6 w-6" />
            <h1 className="text-lg font-medium">AI Learning Assistant</h1>
          </div>
          <div>
            <Avatar className="h-8 w-8">
              <AvatarImage alt="User Avatar" src="/placeholder-avatar.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
          </div>
        </header>
        <main className="flex-1 overflow-auto p-4">
          <div className="space-y-4">
            <div className="flex justify-start">
              <div className="max-w-[75%] rounded-lg rounded-bl-none bg-gray-100 p-3 text-gray-900 dark:bg-gray-800 dark:text-gray-50">
                <p>Hello! How can I assist you with your learning today?</p>
              </div>
            </div>
            <div className="flex justify-end">
              <div className="max-w-[75%] rounded-lg rounded-br-none bg-blue-500 p-3 text-white">
                <p>
                  I'm looking to learn more about machine learning. Can you give me an overview of the key concepts?
                </p>
              </div>
            </div>
            <div className="flex justify-start">
              <div className="max-w-[75%] rounded-lg rounded-bl-none bg-gray-100 p-3 text-gray-900 dark:bg-gray-800 dark:text-gray-50">
                <p>
                  Absolutely! Machine learning is a field of artificial intelligence that enables computers to learn and
                  improve from experience without being explicitly programmed. The key concepts include:
                </p>
                <ul className="mt-2 list-disc pl-5">
                  <li>Supervised learning</li>
                  <li>Unsupervised learning</li>
                  <li>Neural networks</li>
                  <li>Regression</li>
                  <li>Classification</li>
                </ul>
              </div>
            </div>
            <div className="flex justify-end">
              <div className="max-w-[75%] rounded-lg rounded-br-none bg-blue-500 p-3 text-white">
                <p>
                  That's really helpful, thank you! Can you give me a bit more detail on supervised and unsupervised
                  learning?
                </p>
              </div>
            </div>
          </div>
        </main>
        <div className="flex items-center bg-gray-100 px-4 py-3 dark:bg-gray-800">
          <Input
            className="flex-1 rounded-md border-none bg-transparent py-2 pr-2 text-gray-900 placeholder:text-gray-500 focus:outline-none dark:text-gray-50 dark:placeholder:text-gray-400"
            placeholder="Type your message..."
            type="text"
          />
          <Button className="ml-2">
            <SendIcon className="h-5 w-5" />
          </Button>
        </div>
      </div>
    </div>
  )
}

function BotIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 8V4H8" />
      <rect width="16" height="12" x="4" y="8" rx="2" />
      <path d="M2 14h2" />
      <path d="M20 14h2" />
      <path d="M15 13v2" />
      <path d="M9 13v2" />
    </svg>
  )
}


function PlusIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function SendIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}
