/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/a99HNBpqRkB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function CourseDetailPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-gray-900 text-white py-4 px-6 flex items-center justify-between sticky top-0 z-10">
        <Link className="flex items-center gap-2 font-semibold" href="#">
          <BookIcon className="w-6 h-6" />
          <span>Web Development Course</span>
        </Link>
        <Link className="text-gray-400 hover:text-white" href="#">
          <XIcon className="w-6 h-6" />
          <span className="sr-only">Close</span>
        </Link>
      </header>
      <div className="flex flex-1">
        <div className="bg-gray-100 dark:bg-gray-800 w-64 border-r border-gray-200 dark:border-gray-700 p-6 sticky top-0 h-screen overflow-y-auto">
          <h2 className="text-lg font-semibold mb-4">All Courses</h2>
          <nav>
            <ul className="space-y-2">
              <li>
                <Link
                  className="flex items-center gap-3 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-200 font-medium"
                  href="#"
                >
                  <BookIcon className="w-5 h-5" />
                  <span>Introduction to Web Development</span>
                </Link>
              </li>
              <li>
                <Link
                  className="flex items-center gap-3 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-200 font-medium"
                  href="#"
                >
                  <BookIcon className="w-5 h-5" />
                  <span>Advanced CSS Techniques</span>
                </Link>
              </li>
              <li>
                <Link
                  className="flex items-center gap-3 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-200 font-medium"
                  href="#"
                >
                  <BookIcon className="w-5 h-5" />
                  <span>Mastering JavaScript</span>
                </Link>
              </li>
              <li>
                <Link
                  className="flex items-center gap-3 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-200 font-medium"
                  href="#"
                >
                  <BookIcon className="w-5 h-5" />
                  <span>Responsive Web Design</span>
                </Link>
              </li>
              <li>
                <Link
                  className="flex items-center gap-3 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-200 font-medium"
                  href="#"
                >
                  <BookIcon className="w-5 h-5" />
                  <span>React Fundamentals</span>
                </Link>
              </li>
            </ul>
          </nav>
        </div>
        <div className="flex-1 p-6">
          <div className="max-w-6xl mx-auto px-4 py-12 md:py-16 lg:py-20">
            <div className="grid md:grid-cols-2 gap-8 lg:gap-12">
              <div>
                <h1 className="text-3xl md:text-4xl font-bold mb-4">Introduction to Web Development</h1>
                <p className="text-gray-500 dark:text-gray-400 mb-6">
                  Learn the fundamentals of web development, including HTML, CSS, and JavaScript. This course covers the
                  basics of building responsive and accessible websites.
                </p>
                <div className="grid gap-6">
                  <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
                    <div className="flex items-center gap-3 mb-2">
                      <BookIcon className="w-6 h-6 text-gray-900 dark:text-gray-50" />
                      <h3 className="text-lg font-semibold">Lectures</h3>
                    </div>
                    <ul className="space-y-3">
                      <li>
                        <div className="flex items-center justify-between">
                          <div>
                            <h4 className="font-medium">Introduction to HTML</h4>
                            <p className="text-gray-500 dark:text-gray-400 text-sm">
                              Learn the basic structure and syntax of HTML.
                            </p>
                          </div>
                          <PlayIcon className="w-5 h-5 text-gray-900 dark:text-gray-50" />
                        </div>
                      </li>
                      <li>
                        <div className="flex items-center justify-between">
                          <div>
                            <h4 className="font-medium">CSS Fundamentals</h4>
                            <p className="text-gray-500 dark:text-gray-400 text-sm">
                              Understand the basics of CSS and how to style your web pages.
                            </p>
                          </div>
                          <PlayIcon className="w-5 h-5 text-gray-900 dark:text-gray-50" />
                        </div>
                      </li>
                      <li>
                        <div className="flex items-center justify-between">
                          <div>
                            <h4 className="font-medium">JavaScript Essentials</h4>
                            <p className="text-gray-500 dark:text-gray-400 text-sm">
                              Explore the fundamentals of JavaScript and how to add interactivity to your websites.
                            </p>
                          </div>
                          <PlayIcon className="w-5 h-5 text-gray-900 dark:text-gray-50" />
                        </div>
                      </li>
                    </ul>
                  </div>
                  <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
                    <div className="flex items-center gap-3 mb-2">
                      <MailQuestionIcon className="w-6 h-6 text-gray-900 dark:text-gray-50" />
                      <h3 className="text-lg font-semibold">Quizzes</h3>
                    </div>
                    <ul className="space-y-3">
                      <li>
                        <div className="flex items-center justify-between">
                          <div>
                            <h4 className="font-medium">HTML Quiz</h4>
                            <p className="text-gray-500 dark:text-gray-400 text-sm">
                              Test your understanding of HTML concepts.
                            </p>
                          </div>
                          <MailQuestionIcon className="w-5 h-5 text-gray-900 dark:text-gray-50" />
                        </div>
                      </li>
                      <li>
                        <div className="flex items-center justify-between">
                          <div>
                            <h4 className="font-medium">CSS Quiz</h4>
                            <p className="text-gray-500 dark:text-gray-400 text-sm">
                              Assess your knowledge of CSS properties and techniques.
                            </p>
                          </div>
                          <MailQuestionIcon className="w-5 h-5 text-gray-900 dark:text-gray-50" />
                        </div>
                      </li>
                      <li>
                        <div className="flex items-center justify-between">
                          <div>
                            <h4 className="font-medium">JavaScript Quiz</h4>
                            <p className="text-gray-500 dark:text-gray-400 text-sm">
                              Evaluate your understanding of JavaScript fundamentals.
                            </p>
                          </div>
                          <MailQuestionIcon className="w-5 h-5 text-gray-900 dark:text-gray-50" />
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div className="hidden md:block">
                <img
                  alt="Course Thumbnail"
                  className="rounded-lg object-cover w-full h-full"
                  height={400}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "600/400",
                    objectFit: "cover",
                  }}
                  width={600}
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function BookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  )
}


function MailQuestionIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 10.5V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v12c0 1.1.9 2 2 2h12.5" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
      <path d="M18 15.28c.2-.4.5-.8.9-1a2.1 2.1 0 0 1 2.6.4c.3.4.5.8.5 1.3 0 1.3-2 2-2 2" />
      <path d="M20 22v.01" />
    </svg>
  )
}


function PlayIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="6 3 20 12 6 21 6 3" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
