/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/uPrTgDkFRJm
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"

export function Dashboard() {
  return (
    <div className="flex h-full w-full">
      
      <div className="flex flex-1 flex-col">
        
        <main className="flex-1 bg-gray-100 dark:bg-gray-900 p-4 md:p-6">
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            <Card>
              <CardHeader>
                <CardTitle>Current Courses</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  <Link className="flex items-center gap-4" href="/courses/1">
                    <img
                      alt="Course Thumbnail"
                      className="rounded-md"
                      height="64"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "64/64",
                        objectFit: "cover",
                      }}
                      width="64"
                    />
                    <div>
                      <h3 className="text-lg font-medium">Introduction to AI</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">Beginner</p>
                      <div className="mt-2 flex items-center gap-2">
                        <div className="h-2 w-full rounded-full bg-gray-200 dark:bg-gray-800">
                          <div className="h-full w-2/3 rounded-full bg-blue-500" />
                        </div>
                        <span className="text-sm text-gray-500 dark:text-gray-400">67%</span>
                      </div>
                    </div>
                  </Link>
                  <div className="flex items-center gap-4">
                    <img
                      alt="Course Thumbnail"
                      className="rounded-md"
                      height="64"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "64/64",
                        objectFit: "cover",
                      }}
                      width="64"
                    />
                    <div>
                      <h3 className="text-lg font-medium">Machine Learning</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">Intermediate</p>
                      <div className="mt-2 flex items-center gap-2">
                        <div className="h-2 w-full rounded-full bg-gray-200 dark:bg-gray-800">
                          <div className="h-full w-1/2 rounded-full bg-blue-500" />
                        </div>
                        <span className="text-sm text-gray-500 dark:text-gray-400">50%</span>
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Progress</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  <div>
                    <h3 className="text-lg font-medium">Total Courses Completed</h3>
                    <p className="text-4xl font-bold">12</p>
                  </div>
                  <div>
                    <h3 className="text-lg font-medium">Total Hours Studied</h3>
                    <p className="text-4xl font-bold">84</p>
                  </div>
                  <div>
                    <h3 className="text-lg font-medium">Certificates Earned</h3>
                    <p className="text-4xl font-bold">6</p>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Recommendations</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  <div className="flex items-center gap-4">
                    <img
                      alt="Course Thumbnail"
                      className="rounded-md"
                      height="64"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "64/64",
                        objectFit: "cover",
                      }}
                      width="64"
                    />
                    <div>
                      <h3 className="text-lg font-medium">Deep Learning</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">Intermediate</p>
                      <Button className="mt-2" size="sm">
                        Enroll
                      </Button>
                    </div>
                  </div>
                  <div className="flex items-center gap-4">
                    <img
                      alt="Course Thumbnail"
                      className="rounded-md"
                      height="64"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "64/64",
                        objectFit: "cover",
                      }}
                      width="64"
                    />
                    <div>
                      <h3 className="text-lg font-medium">Natural Language Processing</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">Advanced</p>
                      <Button className="mt-2" size="sm">
                        Enroll
                      </Button>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Kartenstapel</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  <Link className="flex items-center gap-4" href="/courses/1">
                    <img
                      alt="Course Thumbnail"
                      className="rounded-md"
                      height="64"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "64/64",
                        objectFit: "cover",
                      }}
                      width="64"
                    />
                    <div>
                      <h3 className="text-lg font-medium">Introduction to AI</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">Beginner</p>
                      <div className="mt-2 flex items-center gap-2">
                        <div className="h-2 w-full rounded-full bg-gray-200 dark:bg-gray-800">
                          <div className="h-full w-2/3 rounded-full bg-blue-500" />
                        </div>
                        <span className="text-sm text-gray-500 dark:text-gray-400">67%</span>
                      </div>
                    </div>
                  </Link>
                  <div className="flex items-center gap-4">
                    <img
                      alt="Course Thumbnail"
                      className="rounded-md"
                      height="64"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "64/64",
                        objectFit: "cover",
                      }}
                      width="64"
                    />
                    <div>
                      <h3 className="text-lg font-medium">Machine Learning</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">Intermediate</p>
                      <div className="mt-2 flex items-center gap-2">
                        <div className="h-2 w-full rounded-full bg-gray-200 dark:bg-gray-800">
                          <div className="h-full w-1/2 rounded-full bg-blue-500" />
                        </div>
                        <span className="text-sm text-gray-500 dark:text-gray-400">50%</span>
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Quizze</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  <Link className="flex items-center gap-4" href="/courses/1">
                    <img
                      alt="Course Thumbnail"
                      className="rounded-md"
                      height="64"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "64/64",
                        objectFit: "cover",
                      }}
                      width="64"
                    />
                    <div>
                      <h3 className="text-lg font-medium">Introduction to AI</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">Beginner</p>
                      <div className="mt-2 flex items-center gap-2">
                        <div className="h-2 w-full rounded-full bg-gray-200 dark:bg-gray-800">
                          <div className="h-full w-2/3 rounded-full bg-blue-500" />
                        </div>
                        <span className="text-sm text-gray-500 dark:text-gray-400">67%</span>
                      </div>
                    </div>
                  </Link>
                  <div className="flex items-center gap-4">
                    <img
                      alt="Course Thumbnail"
                      className="rounded-md"
                      height="64"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "64/64",
                        objectFit: "cover",
                      }}
                      width="64"
                    />
                    <div>
                      <h3 className="text-lg font-medium">Machine Learning</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">Intermediate</p>
                      <div className="mt-2 flex items-center gap-2">
                        <div className="h-2 w-full rounded-full bg-gray-200 dark:bg-gray-800">
                          <div className="h-full w-1/2 rounded-full bg-blue-500" />
                        </div>
                        <span className="text-sm text-gray-500 dark:text-gray-400">50%</span>
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </main>
      </div>
    </div>
  )
}

