/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/gxGiKdN4SbC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function QuizQuestionCard() {
  return (
    <main className="flex flex-col items-center justify-center h-full bg-gray-100 dark:bg-gray-900">
      <div className="max-w-3xl w-full px-6 py-12 bg-white rounded-lg shadow-lg dark:bg-gray-800">
        <div className="space-y-6">
          <div className="text-center">
            <h1 className="text-3xl font-bold text-gray-900 dark:text-gray-100">Multiple Choice Quiz</h1>
            <p className="mt-4 text-gray-600 dark:text-gray-400">Test your knowledge with this fun quiz!</p>
          </div>
          <div className="space-y-8">
            <div className="bg-gray-50 p-6 rounded-lg dark:bg-gray-900">
              <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100">Question 1</h2>
              <p className="mt-2 text-gray-600 dark:text-gray-400">What is the capital of France?</p>
              <div className="mt-6 grid grid-cols-2 gap-4">
                <label className="flex items-center bg-white rounded-lg shadow-md p-4 cursor-pointer dark:bg-gray-800 dark:hover:bg-gray-750 transition-colors">
                  <input
                    className="form-radio text-indigo-600 focus:ring-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:checked:bg-indigo-500 dark:checked:border-indigo-500"
                    name="question1"
                    type="radio"
                  />
                  <span className="ml-3 text-gray-700 dark:text-gray-400 font-medium">Paris</span>
                </label>
                <label className="flex items-center bg-white rounded-lg shadow-md p-4 cursor-pointer dark:bg-gray-800 dark:hover:bg-gray-750 transition-colors">
                  <input
                    className="form-radio text-indigo-600 focus:ring-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:checked:bg-indigo-500 dark:checked:border-indigo-500"
                    name="question1"
                    type="radio"
                  />
                  <span className="ml-3 text-gray-700 dark:text-gray-400 font-medium">London</span>
                </label>
                <label className="flex items-center bg-white rounded-lg shadow-md p-4 cursor-pointer dark:bg-gray-800 dark:hover:bg-gray-750 transition-colors">
                  <input
                    className="form-radio text-indigo-600 focus:ring-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:checked:bg-indigo-500 dark:checked:border-indigo-500"
                    name="question1"
                    type="radio"
                  />
                  <span className="ml-3 text-gray-700 dark:text-gray-400 font-medium">Berlin</span>
                </label>
                <label className="flex items-center bg-white rounded-lg shadow-md p-4 cursor-pointer dark:bg-gray-800 dark:hover:bg-gray-750 transition-colors">
                  <input
                    className="form-radio text-indigo-600 focus:ring-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:checked:bg-indigo-500 dark:checked:border-indigo-500"
                    name="question1"
                    type="radio"
                  />
                  <span className="ml-3 text-gray-700 dark:text-gray-400 font-medium">Rome</span>
                </label>
              </div>
            </div>
            <div className="flex justify-end">
              <Button size="sm" variant="outline">
                Submit Answers
              </Button>
            </div>
          </div>
        </div>
      </div>
    </main>
  )
}
